### ISSUE TITLE
Statistics data are not visible with Firefox mobile

### ISSUE THREAD

**Issue by pcvolkmer** [thm-projects/arsnova-mobile#38]
Using Firefox mobile 40.0, statistics data are not visible.

![screenshot_2015-08-15-11-00-36](https://cloud.githubusercontent.com/assets/5081579/9288258/1066cf10-433e-11e5-8824-9ebce9f76509.png)

**Comment by dgerhardt** [comment]
I can't reproduce this on my Nexus 5, Android 5.1.1. Statistics are fine here with FF40:

![arsnova-mobile-statistics-android5-ff40](https://cloud.githubusercontent.com/assets/3731006/9288282/02a2bd16-433f-11e5-97e5-ea7864d52779.png)

Since there is nothing special about the loading of statistics compared to other data I guess this is not browser related. Is this issue reproducible on your device and can you rule out the possibility that there might have been a connection problem?

**Comment by pcvolkmer** [comment]
Well, the fact that an issue does not exists on some devices does not prove that the issue does not exist at all, right?

**Comment by dgerhardt** [comment]
There is always the possibility that a issue is browser/device related. But we should rule out other sources first since it is impossible to test on all existing combinations of devices and browsers.

**Comment by pcvolkmer** [comment]
That's right, I just reported an issue occurring on one of my devices to improve projects quality.

**Comment by dgerhardt** [comment]
Is this issue also occurring when using landscape mode?

**Comment by pcvolkmer** [comment]
Yes.

One additional information: Closing FF mobile, cleaning all cookies and local storage, restarting FF and visiting ARSnova again solves this issue for me. It might have been a cache related error. Just reloading ARSnova did not help.

**Comment by dhx** [comment]
When doing the update from 2.1 to 2.2 here we got a similar problem with FF (maybe similar cause). The user could not enter a session anymore. Reloading ARSnova (in the ARSnova system menu) did not help, cleaning the cache + local storage and restarting FF finally solved it.

**Comment by kqc-real** [comment]
@dgerhardt : Please add a note in the release notes of v2.2 concerning the comment of dhx.

**Comment by dgerhardt** [comment]
Has not been reproduced in a long time so I'm closing this.
