### ISSUE TITLE
LaTeX display issues: Chrome displays pipe "|"

### ISSUE THREAD

**Issue by mjg** [thm-projects/arsnova-mobile#71]
ARSnova 2.4.3 produces an extra pipe symbol "|" after each piece of LaTeX display in Chrome 55: compare the renderings below for Chrome 55 versus Firefox 50 (Linux: Fedora 24). The code is always `\(x^2\)`.

(Also, Firefox messes up the "close" button, and I seem to remember that TeX-code used to work in answers, too, but may be wrong about that.)

![chrome55](https://cloud.githubusercontent.com/assets/233215/21189063/bbb03e9c-c21d-11e6-8618-bbb31986e441.png) 
![ff50](https://cloud.githubusercontent.com/assets/233215/21189064/bbb4cd7c-c21d-11e6-9aba-a0c1fc6b3598.png)

**Comment by dgerhardt** [comment]
This is an issue in older versions of the math rendering library MathJax: https://github.com/mathjax/MathJax/issues/1300.

You can switch to version 2.7 by changing the URL in [arsnova.properties](https://github.com/thm-projects/arsnova-backend/blob/2.4/src/main/resources/arsnova.properties.example#L196).

We should probably update the config example since we have been using a newer version ourselves for arsnova.eu for some time.

**Comment by dgerhardt** [comment]
Regarding formatting for answers:
https://github.com/thm-projects/arsnova-backend/blob/2.4/src/main/resources/arsnova.properties.example#L235

I was not able to reproduce the issue with the save button in FF50. Can you reproduce it on arsnova.eu?

**Comment by mjg** [comment]
Thanks for the comments. All tests were against arsnova.elsa.uni-hannover.de, here ARSnova is being evaluated this term. It's running ARSnova 2.4.3.

On arsnova.eu, math in the question displays fine with Firefox as well as Chrome, and the save button is there. So I'll raise these issues locally.
